{% set name = "oneat" %}
{% set version = "6.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/oneat-{{ version }}.tar.gz
  sha256: 63114c2f9f5792ed02dca2b5034a2de3f5fba1e9394ce8dd5b95f0335612f213

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - caped-ai-metrics
    - dask-core
    - hydra-core
    - imagecodecs
    - matplotlib-base
    - napari
    - napari-animation
    - natsort
    - oneat-augmentations
    - pydot
    - python >=3.8
    - python-graphviz
    - pandas
    - scikit-learn
    - scipy
    - seaborn
    - tifffile
    - vollseg-napari

test:
  imports:
    - oneat
  commands:
    - pip list
    # - pip check  # Fails due to opencv-python-headless and sklearn
  requires:
    - pip

about:
  home: https://github.com/Kapoorlabs-CAPED/oneat
  summary: |
    Action classification for TZYX/TYX shaped images,
    Static classification for TYX/YX shaped images
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - kapoorlab
