{% set name = "oneat" %}
{% set version = "6.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/oneat-{{ version }}.tar.gz
  sha256: 75b1782e498c2a16b8cd329ed88280f59abcc1e8b6eb47a0201c2412bd21e8f4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - caped-ai-metrics
    - dask-core
    - hydra-core
    - imagecodecs
    - matplotlib-base
    - napari
    - napari-animation
    - natsort
    - oneat-augmentations
    - pydot
    - python >={{ python_min }}
    - python-graphviz
    - pandas
    - scikit-learn
    - scipy
    - seaborn
    - tifffile
    - vollseg-napari

test:
  imports:
    - oneat
  commands:
    - pip list
    # - pip check  # Fails due to opencv-python-headless and sklearn
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Kapoorlabs-CAPED/oneat
  summary: |
    Action classification for TZYX/TYX shaped images,
    Static classification for TYX/YX shaped images
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - kapoorlab
